name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

categories:
  - title: 'Features'
    label: 'type/enhancement'
  - title: 'Bug fixes'
    label: 'type/bug'
  - title: 'Documentation'
    label: 'type/documentation'
  - title: 'Dependencies'
    collapse-after: 3
    label: 'dependencies'

version-resolver:
  default: minor
  major:
    labels:
      - major
  minor:
    labels:
      - type/enhancement
  patch:
    labels:
      - type/bug
      - type/documentation
      - dependencies

autolabeler:
  - label: 'type/bug'
    title:
      - '/fix.*/'
  - label: 'type/enhancement'
    title:
      - '/feat.*/'
      - '/fix.*/'
      - '/ci.*/'
      - '/chore.*/'
  - label: 'type/documentation'
    files:
      - '*.md'
    title:
      - '/docs.*/'
  - label: 'dependencies'
    title: 
      - '/chore\(update\).*/'

exclude-labels:
  - skip-changelog

template: |
  ## What's changed
  
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
