{
 "title": "Morty",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Function invocations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(morty_function_invocation)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Function invocations (warm instances)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(morty_function_invocation{isColdStart=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Function invocations (cold start)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(morty_function_invocation{isColdStart=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of invocations per function",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(morty_function_invocation) by (function)",
     "legendFormat": "{{function}}"
    }
   ]
  },
  {
   "title": "Average invocation time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(morty_function_invocation_duration_sum{isColdStart=\"true\"}) / sum(morty_function_invocation_duration_count{isColdStart=\"true\"})",
     "legendFormat": "Cold start"
    },
    {
     "expr": "sum(morty_function_invocation_duration_sum{isColdStart=\"false\"}) / sum(morty_function_invocation_duration_count{isColdStart=\"false\"})",
     "legendFormat": "Warm instances"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Average invocation over time (Cold Start)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(morty_function_invocation_duration_sum{isColdStart=\"true\"}[$__range])) / sum(rate(morty_function_invocation_duration_count{isColdStart=\"true\"}[$__range]))",
     "legendFormat": "Cold start"
    }
   ]
  },
  {
   "title": "Average invocation over time (Warm instances)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(morty_function_invocation_duration_sum{isColdStart=\"false\"}[$__range])) / sum(rate(morty_function_invocation_duration_count{isColdStart=\"false\"}[$__range]))",
     "legendFormat": "Warm instances"
    }
   ]
  }
 ]
}