openapi: 3.0.3
info:
  description: This document aims to provide a simple and clear Morty Function Registry
    endpoints documentation.
  title: Morty Registry - API Documentation
  version: 1.1.0
externalDocs:
  description: Morty Function Registry on Github.
  url: https://github.com/morty-faas/registry
servers:
- url: /
tags:
- description: Functions API endpoints
  name: Functions
paths:
  /v1/functions/build:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BuildRequest'
      responses:
        "200":
          content:
            application/text:
              schema:
                $ref: '#/components/schemas/BuildResponse'
          description: The function build was successful.
      summary: Build a function and push the image into the registry.
      tags:
      - Functions
  /v1/functions/{id}/{version}:
    get:
      parameters:
      - description: The identifier of the function to download.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - description: The version of the function to download.
        explode: false
        in: path
        name: version
        required: true
        schema:
          type: string
        style: simple
      responses:
        "302":
          description: Redirection on a pre-signed URL allowing the caller to download
            the function image.
        "500":
          description: An internal server error ocurred. Please check the logs of
            your registry for more details.
      summary: Get a download link for the image of the given function
      tags:
      - Functions
components:
  schemas:
    BuildRequest:
      properties:
        runtime:
          description: The name of the runtime to use.
          example: python-3
          type: string
        name:
          description: The name of the function.
          example: my-python-func
          type: string
        version:
          description: The version of the function. This should be a semantic version.
          type: string
        archive:
          format: binary
          type: string
      type: object
    BuildResponse:
      description: The URI to call on this server to retrieve a download link for
        this function image.
      type: string
