/*
Morty APIs

This document contains the specification of the public-facing Morty APIs. For function invocation, please see the project README here: https://github.com/morty-faas/morty/controller#readme 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type ConfigurationApi interface {

	/*
	GetServerMetadata Get informations about the server such as version, build commit etc.

	Get informations about the server such as version, build commit etc.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ConfigurationApiGetServerMetadataRequest
	*/
	GetServerMetadata(ctx context.Context) ConfigurationApiGetServerMetadataRequest

	// GetServerMetadataExecute executes the request
	//  @return ServerMetadata
	GetServerMetadataExecute(r ConfigurationApiGetServerMetadataRequest) (*ServerMetadata, *http.Response, error)
}

// ConfigurationApiService ConfigurationApi service
type ConfigurationApiService service

type ConfigurationApiGetServerMetadataRequest struct {
	ctx context.Context
	ApiService ConfigurationApi
}

func (r ConfigurationApiGetServerMetadataRequest) Execute() (*ServerMetadata, *http.Response, error) {
	return r.ApiService.GetServerMetadataExecute(r)
}

/*
GetServerMetadata Get informations about the server such as version, build commit etc.

Get informations about the server such as version, build commit etc.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ConfigurationApiGetServerMetadataRequest
*/
func (a *ConfigurationApiService) GetServerMetadata(ctx context.Context) ConfigurationApiGetServerMetadataRequest {
	return ConfigurationApiGetServerMetadataRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ServerMetadata
func (a *ConfigurationApiService) GetServerMetadataExecute(r ConfigurationApiGetServerMetadataRequest) (*ServerMetadata, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ServerMetadata
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ConfigurationApiService.GetServerMetadata")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/.well-known/morty.json"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
