/*
Morty APIs

This document contains the specification of the public-facing Morty APIs. For function invocation, please see the project README here: https://github.com/morty-faas/morty/controller#readme 

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the CreateFunctionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFunctionRequest{}

// CreateFunctionRequest struct for CreateFunctionRequest
type CreateFunctionRequest struct {
	Name *string `json:"name,omitempty"`
	Image *string `json:"image,omitempty"`
}

// NewCreateFunctionRequest instantiates a new CreateFunctionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFunctionRequest() *CreateFunctionRequest {
	this := CreateFunctionRequest{}
	return &this
}

// NewCreateFunctionRequestWithDefaults instantiates a new CreateFunctionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFunctionRequestWithDefaults() *CreateFunctionRequest {
	this := CreateFunctionRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateFunctionRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFunctionRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateFunctionRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateFunctionRequest) SetName(v string) {
	o.Name = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *CreateFunctionRequest) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFunctionRequest) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *CreateFunctionRequest) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *CreateFunctionRequest) SetImage(v string) {
	o.Image = &v
}

func (o CreateFunctionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFunctionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	return toSerialize, nil
}

type NullableCreateFunctionRequest struct {
	value *CreateFunctionRequest
	isSet bool
}

func (v NullableCreateFunctionRequest) Get() *CreateFunctionRequest {
	return v.value
}

func (v *NullableCreateFunctionRequest) Set(val *CreateFunctionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFunctionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFunctionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFunctionRequest(val *CreateFunctionRequest) *NullableCreateFunctionRequest {
	return &NullableCreateFunctionRequest{value: val, isSet: true}
}

func (v NullableCreateFunctionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFunctionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


