/*
Morty APIs

This document contains the specification of the public-facing Morty APIs. For function invocation, please see the project README here: https://github.com/morty-faas/morty/controller#readme 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the CreateFunctionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFunctionRequest{}

// CreateFunctionRequest struct for CreateFunctionRequest
type CreateFunctionRequest struct {
	Name string `json:"name"`
	Version string `json:"version"`
	Image string `json:"image"`
}

// NewCreateFunctionRequest instantiates a new CreateFunctionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFunctionRequest(name string, version string, image string) *CreateFunctionRequest {
	this := CreateFunctionRequest{}
	this.Name = name
	this.Version = version
	this.Image = image
	return &this
}

// NewCreateFunctionRequestWithDefaults instantiates a new CreateFunctionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFunctionRequestWithDefaults() *CreateFunctionRequest {
	this := CreateFunctionRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateFunctionRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateFunctionRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateFunctionRequest) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *CreateFunctionRequest) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *CreateFunctionRequest) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *CreateFunctionRequest) SetVersion(v string) {
	o.Version = v
}

// GetImage returns the Image field value
func (o *CreateFunctionRequest) GetImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *CreateFunctionRequest) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *CreateFunctionRequest) SetImage(v string) {
	o.Image = v
}

func (o CreateFunctionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFunctionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	toSerialize["image"] = o.Image
	return toSerialize, nil
}

type NullableCreateFunctionRequest struct {
	value *CreateFunctionRequest
	isSet bool
}

func (v NullableCreateFunctionRequest) Get() *CreateFunctionRequest {
	return v.value
}

func (v *NullableCreateFunctionRequest) Set(val *CreateFunctionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFunctionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFunctionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFunctionRequest(val *CreateFunctionRequest) *NullableCreateFunctionRequest {
	return &NullableCreateFunctionRequest{value: val, isSet: true}
}

func (v NullableCreateFunctionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFunctionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


